---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-a
spec:
  replicas: 1
  selector:
    matchLabels:
      application: metrics-a
  template:
    metadata:
      labels:
        application: metrics-a
    spec:
      containers:
        - image: quay.io/skupper/simple-prom-metrics
          name: metrics-a
          imagePullPolicy: IfNotPresent
---
