---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: metrics-b
    spec:
      containers:
        - image: quay.io/skupper/simple-prom-metrics
          name: metrics-b
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-b
  annotations:
    skupper.io/proxy: tcp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: metrics-b
---
