---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-b
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: metrics-b
    spec:
      containers:
        - image: quay.io/skupper/simple-prom-metrics
          name: metrics-b
          imagePullPolicy: IfNotPresent
---
